### ISSUE TITLE
Library is licensed as GPL-3

### ISSUE THREAD

**Issue by cilice** [phegman/v-scroll-lock#14]
Hey,

This library is licensed as GPL-3 and is being used in [chakra-ui/vue](https://github.com/chakra-ui/chakra-ui-vue). Unfortunately, this blocks us from using chakra ui in a commercial product.

Would you consider changing the license to something more permitting? 💖

Apache-2.0 works well for us, MIT would too.

**Comment by phegman** [comment]
Yep, no problem! I have no intention of restricting usage of this package so happy to change! 

Just merged a change to Apache-2.0, hope that helps!

**Comment by cilice** [comment]
@phegman Thank you so much! 🎉
