### ISSUE TITLE
How can I set reserveScrollBarGap

### ISSUE THREAD

**Issue by doutatsu** [phegman/v-scroll-lock#6]
I am not quite sure how to apply this option with this directive. Hence, I am currently having to just use body-scroll-lock directly

**Comment by phegman** [comment]
This directive does not yet support passing of `body-scroll-lock` options. I would like to implement but haven't had the time. Shouldn't be too complicated to add, feel free to open up a PR!

**Comment by wspwebben** [comment]
+1 on this

**Comment by phegman** [comment]
Thanks to @tnifey's contribution this feature is now available in v1.2.0 🎉
