### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by acerspyro** [phegman/v-scroll-lock#7]
The ``v-scroll-lock`` package does not provide its own TypeScript definitions, and none are available from DefinitelyTyped.

The only way to use this package with TypeScript at the moment is by using a shim .d.ts file.

**Comment by phegman** [comment]
Looks like the `types` property was missing in `package.json`. This should be fixed in the latest version v1.1.1. Give that a try and let me know if you still have issues!

**Comment by acerspyro** [comment]
Thanks! I'll let you know by the end of the week :)
